### ISSUE TITLE
Material Icons Support

### ISSUE THREAD

**Issue by PaulBGD** [neverpanic/google-font-download#10]
So while this script downloads them fine, there's 1 additional CSS selector that's included for `.material-icons` which adds some ligature support: https://fonts.googleapis.com/css?family=Material+Icons

Not sure if adding that is in the scope of this script, but thought I'd bring it up.

**Comment by neverpanic** [comment]
I guess I could try to look for other CSS rules and copy them verbatim if present, but at the moment this is not urgent enough for me to pursue. If anybody wants to contribute a patch for this I'll happily merge one, but I don't have time to spend on this, sorry.
