### ISSUE TITLE
Support "Fontname:###i"

### ISSUE THREAD

**Issue by skylarmt** [neverpanic/google-font-download#11]
I downloaded a font by passing `"Fontname:300" "Fontname:300i"` etc.  This resulted in CSS with `font-weight: 300i` and `font-style: normal`, which isn't good.

**Comment by neverpanic** [comment]
I don't think I'll spend time on supporting this. If I implemented support for `i`, would I also have to support specifying `Fontname:300normal`, `Fontname:300regular`, `Fontname:300ital` and `Fontname:300garbabe` (which all will give you a valid reply from Google's servers, btw).

Instead, I'll adjust documentation to point out that only font weights and the special suffix "italic" is supported.

Of course, if you want to submit a pull request, that's always welcome.

**Comment by skylarmt** [comment]
I think `i` is a special case because [that's what Google uses.](https://i.imgur.com/VnfERTN.png)
