### ISSUE TITLE
SVG download fails & kills bash

### ISSUE THREAD

**Issue by blueberry-media** [neverpanic/google-font-download#17]
On multi fonts download the script will stop because curl gets a 500 error 
check with "Amiri:regular" (svg fails) 

Possible solution is catching curl error 

> curl -sfL "$file" -o "${fontnameescaped}.$uakey" **|| printf >&2 " failed: %s\n" "${fontnameescaped}.$uakey"**

**Comment by neverpanic** [comment]
Please re-test with the current master.
