### ISSUE TITLE
Seemed like this didn't want to work on OS X

### ISSUE THREAD

**Issue by MikeiLL** [neverpanic/google-font-download#18]
Ran make and got a bunch of error messages, but now they're lost. I had forgotten about it and went another route, but came across again in left-open browser window.

Should this work on OS X?

Thanks much, man.

**Comment by neverpanic** [comment]
Yes, this works on macOS (as it was developed there). You don't need to run make, though, since it will only run the tests. You can directly run the script.

**Comment by beaumartinez** [comment]
I'm on macOS and with the default getopt and grep it doesn't work out of the box. You can install GNU getopt and grep and use those though (`brew install gnu-getopt grep` and follow the caveats to add those to your `PATH`).

**Comment by neverpanic** [comment]
The script does require Bash 4.x, which is not preinstalled on macOS. However, with Bash 4.x, it does not need any other extra tools (although you might get a warning on getopt):

```
$> PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin /opt/local/bin/bash ~/Development/google-font-download/google-font-download "'Open Sans:300'"
Warning: Old getopt(1) detected.

Your version of getopt(1) does not correctly deal with whitespace and does not support long options. You may have to quote any special character arguments twice. For
example, to download the 'Open Sans' font, use /Users/clemens/Development/google-font-download/google-font-download "'Open Sans'". See
https://github.com/neverpanic/google-font-download/issues/1 for more information.

You should consider upgrading to a more modern version of getopt(1).

Downloading Open Sans:300...woff2 woff eot svg ttf
```
