### ISSUE TITLE
bash error: Line 234: line is not set

### ISSUE THREAD

**Issue by selamhabibi** [neverpanic/google-font-download#19]
Thank you for your work! Most of my fonts I could download very well with the script. However, some URLs cause problems:

Works:
**. /google-font-download --url="https://fonts.googleapis.com/css?family=Lora: 400,700,400italic, 700italic&subset=latin, latin-ext" -o Lora. css**

This URL throws an error:
**./google-font-download --url="http://fonts.googleapis.com/css?family=Source+Code+Pro" -o SourceCodePro.css**

The example from README.md doesn't work for me either:
**./google-font-download --url="https://fonts.google.com/?selection.family=Open+Sans: 300,400,400i, 700,700i"**

Here is the error message:
**Line 234: line is not set.**

Could it be that it is the "+" character within the URL?

Thanks!

**Comment by neverpanic** [comment]
Thanks for the report, should be fixed in 1.4.1.
