### ISSUE TITLE
shellcheck: unable to decommit memory: Invalid argument

### ISSUE THREAD

**Issue by vgarcia007** [neverpanic/google-font-download#24]
On Ubuntu 18.04 make give me this output:

bash -n google-font-download
shellcheck google-font-download
shellcheck: unable to decommit memory: Invalid argument
shellcheck: unable to decommit memory: Invalid argument

**Comment by neverpanic** [comment]
You don't have to run make to use this tool. The `Makefile` is only used during development.

In your case, this seems to be a problem with your installation of shellcheck.

**Comment by vgarcia007** [comment]
Thank you. It worked.
