### ISSUE TITLE
Cannot download woff2 fonts

### ISSUE THREAD

**Issue by hydrapolic** [neverpanic/google-font-download#6]
$ ./google-font-download -f woff2 'Open Sans:300'

Dies here:
...
+ uakey=woff2
+ '[' 0 -eq 0 ']'
+ terminator=';'
+ printf '%s ' woff2
woff2 + '[' woff2 '!=' svg ']'
+ pattern='http:\/\/[^\)]+\.woff2'
++ grep -Eo 'http:\/\/[^\)]+\.woff2'
++ sort -u
++ curl -sf -A 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0' --get --data-urlencode 'family=Open Sans:300' --data-urlencode subset=latin http://fonts.googleapis.com/css
+ file=

This seems to work:
-useragent[woff2]='Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0'
+useragent[woff2]='Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0'

**Comment by neverpanic** [comment]
Can reproduce.

**Comment by hydrapolic** [comment]
Thank you Clemens
